packages:
    - 'packages/types'
    - 'packages/api-redundancy'
    - 'packages/fetch'
    - 'packages/utils'
    - 'packages/core'
    - 'packages/component-utils'
    - 'iconify-icon/icon'
    - 'iconify-icon/*'
    - 'components/*'
    - 'components-css/*'
    - 'components-demo/*'
    - 'components-css-demo/*'
    - 'iconify-icon-demo/*'
    # - 'debug/*'
