<template>
	<section>
		<h1>Alignment (components/Alignment.vue)</h1>
		<div>
			<p>Icon with correct width/heigh ratio:</p>
			<iconify-icon icon="experiment" />
		</div>
		<div>
			<p>Bad width/height ratio, default alignment (slice = false):</p>
			<iconify-icon icon="experiment" width="2em" height="1em" />
			<iconify-icon icon="experiment" width="1em" height="2em" />
		</div>
		<div>
			<p>Slice:</p>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				align="slice"
			/>
		</div>
		<div>
			<p>Slice:</p>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				align="slice"
			/>
		</div>
		<div>
			<p>Left:</p>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				hAlign="left"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				h-align="left"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				horizontalAlign="left"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				horizontal-align="left"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				align="left"
			/>
		</div>
		<div>
			<p>Left with slice:</p>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				hAlign="left"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				h-align="left"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				horizontalAlign="left"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				horizontal-align="left"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				align="left,slice"
			/>
		</div>
		<div>
			<p>Right:</p>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				hAlign="right"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				h-align="right"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				horizontalAlign="right"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				horizontal-align="right"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				align="right"
			/>
		</div>
		<div>
			<p>Right with slice:</p>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				hAlign="right"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				h-align="right"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				horizontalAlign="right"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				horizontal-align="right"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				align="right,slice"
			/>
		</div>
		<div>
			<p>Top:</p>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				verticalAlign="top"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				vertical-align="top"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				v-bind:v-align="'top'"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				align="top"
			/>
		</div>
		<div>
			<p>Top with slice:</p>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				verticalAlign="top"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				vertical-align="top"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				v-bind:v-align="'top'"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				align="top"
				:slice="true"
			/>
		</div>
		<div>
			<p>Bottom:</p>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				verticalAlign="bottom"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				vertical-align="bottom"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				v-bind:v-align="'bottom'"
			/>
			<iconify-icon
				icon="experiment"
				width="1em"
				height="2em"
				align="bottom"
			/>
		</div>
		<div>
			<p>Bottom with slice:</p>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				verticalAlign="bottom"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				vertical-align="bottom"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				v-bind:v-align="'bottom'"
				:slice="true"
			/>
			<iconify-icon
				icon="experiment"
				width="2em"
				height="1em"
				align="bottom,slice"
			/>
		</div>
	</section>
</template>

<script lang="ts">
import { Vue } from 'vue-property-decorator';
import IconifyIcon from '@iconify/vue';

export default Vue.extend({
	components: {
		IconifyIcon,
	},
});
</script>

<style scoped>
svg {
	color: #06a;
	font-size: 32px;
	line-height: 1em;
	margin-right: 8px;
	box-shadow: 0 0 0 1px #ccc;
	vertical-align: top;
}
</style>
